[package]
name = "pc_serial"
version = "0.1.0"
authors = ["Ottis1 <otto.kuusela@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.0.1"
